# Project information
site_name: VBA Grammer
site_url: https://kzrashi.github.io/vba-grammer
site_author: kzrashi
site_description: >-
  This site illustrates grammer of vba programing language for beginners.

# Repository
## GitのURL
repo_url: https://github.com/kzrashi/vba-grammer
## 表示文字列
repo_name: kzrashi/vba-grammer

# Copyright
copyright: "Copyright © 2023-  kzrashi All Rights Reserved."

# Configuration
theme:
  name: material
  language: ja
  # 左上のアイコン
  # logo: assets/python_94570.svg
  icon:
    # Gitリポジトリエリアのアイコン
    repo: fontawesome/brands/github # icon:
    #   logo: assets/python_94570.svg
  #        repo: fontawesome/brands/git-alt

  # ファビコン
  # favicon: assets/python_94570.svg
  # タブ表示を有効.
  features:
    - tabs
    # 今テンスをナビゲーションに含める
    # - toc.integrate

# Plugins
plugins:
  - git-revision-date-localized

#    - search:
#
#      language: 'en, ja'
# 検索インデックスの単語区切り文字設定
#        separator: '[\s\-\.]+'

# Customization
extra:
  generator: false

# Extensions
markdown_extensions:
  # アラート修飾の設定
  - admonition
  # コンテンツ内タブ機能
  - pymdownx.tabbed
  # スーパーフェンス機能の設定
  - pymdownx.superfences
  # コンテンツの折りたたみ設定
  - pymdownx.details

  - pymdownx.critic
  ## ハイライト指定
  - pymdownx.mark

  # - pymdownx.critic.mode: view

  # - pymdownx.betterem:
  #   smart_enable: all

  # - pymdownx.caret
  # - pymdownx.tilde
  # - pymdownx.smartsymbols

  - codehilite:
      #        linenums: true
      guess_lang: false
      use_pygments: false
      noclasses: true
  - toc:
      permalink: true
#    - fontawesome_markdown

# CSS
extra_css:
  - "css/custom.css"

# # Navigation
# nav:
#     - はじめに: index.md
#     - 実行環境: 00_installation.md
#     - 標準出力: 00_print.md
#     - 変数:
#       - 基本            : 01_00_variable.md
#       - 整数型(int)     : 01_01_variable_int.md
#       - 小数点型(float) : 01_02_variable float.md
#       - 真偽型(bool)    : 01_03_variable bool.md
#       - 文字列型(str)    : 01_04_variable_str.md
#     - 標準入力: 01_input.md
#     - 演算    : 01_calcurate.md
#     - リスト  : 03_list.md
#     - 辞書:
#       - 表示    : 04_01_dictionary_disp.md
#       - 追加    : 04_02_dictionary_add.md
#       - 削除    : 04_03_dictionary_delete.md
#     - タプル  : 05_tuples.md
#     - 集合    : 06_set.md
#     - if文    : 12_ifStatements.md
#     - 条件式   :  14_condition.md
#     - for文    :  13_forLoops.md
#     - 検索アルゴリズム: 21_search_algorithm.md
#     # - while文    :
#     # - while文    :
#     # - 関数    :
#     # - 関数    :

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
