# This is a basic workflow to help you get started with Actions

name: github pages

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: python3 -m pip install --upgrade pip
      - run: pip install mkdocs-material
      # - run: pip install mkdocs-git-revision-date-plugin
      - run: pip3 install mkdocs-git-revision-date-localized-plugin

      - name: build
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: mkdocs build

      - name: publishPages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

        # with:
        #   personal_token: ${{ secrets.PERSONAL_TOKEN }}
        #   # デプロイ元リポジトリーとデプロイ先が異なる場合、
        #   # external_repository を指定します。
        #   external_repository: github-user-name/github-repository-name
        #   # publish_branch を指定しない場合、
        #   # gh-pages ブランチにデプロイされます。
        #   publish_branch: master
        #   publish_dir: ./site

      # - run: pip install mkdocs-material
      # - run: mkdocs gh-deploy --force
